### ISSUE TITLE
problem with wcwidth?

### ISSUE THREAD

**Issue by xxl2005** [Pfaeff/pfaeff-comfyui#1]
problen 

`Requirement already satisfied: opencv-python-headless in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 1)) (4.7.0.72)
Requirement already satisfied: diffusers in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 2)) (0.20.2)
Requirement already satisfied: numpy>=1.21.2 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from opencv-python-headless->-r requirements.txt (line 1)) (1.23.5)
Requirement already satisfied: importlib-metadata in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers->-r requirements.txt (line 2)) (6.8.0)
Requirement already satisfied: filelock in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers->-r requirements.txt (line 2)) (3.12.2)
Requirement already satisfied: huggingface-hub>=0.13.2 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers->-r requirements.txt (line 2)) (0.16.4)
Requirement already satisfied: regex!=2019.12.17 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers->-r requirements.txt (line 2)) (2023.8.8)
Requirement already satisfied: requests in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers->-r requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: safetensors>=0.3.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers->-r requirements.txt (line 2)) (0.3.2)
Requirement already satisfied: Pillow in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers->-r requirements.txt (line 2)) (9.5.0)
Requirement already satisfied: fsspec in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub>=0.13.2->diffusers->-r requirements.txt (line 2)) (2023.6.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub>=0.13.2->diffusers->-r requirements.txt (line 2)) (4.66.1)
Requirement already satisfied: pyyaml>=5.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub>=0.13.2->diffusers->-r requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub>=0.13.2->diffusers->-r requirements.txt (line 2)) (4.7.1)
Requirement already satisfied: packaging>=20.9 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub>=0.13.2->diffusers->-r requirements.txt (line 2)) (23.1)
Requirement already satisfied: zipp>=0.5 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from importlib-metadata->diffusers->-r requirements.txt (line 2)) (3.16.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->diffusers->-r requirements.txt (line 2)) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->diffusers->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->diffusers->-r requirements.txt (line 2)) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->diffusers->-r requirements.txt (line 2)) (2023.7.22)
Requirement already satisfied: colorama in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.13.2->diffusers->-r requirements.txt (line 2)) (0.4.6)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
usage: git submodule [--quiet] [--cached]
   or: git submodule [--quiet] add [-b <branch>] [-f|--force] [--name <name>] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] deinit [-f|--force] (--all| [--] <path>...)
   or: git submodule [--quiet] update [--init [--filter=<filter-spec>]] [--remote] [-N|--no-fetch] [-f|--force] [--checkout|--merge|--rebase] [--[no-]recommend-shallow] [--reference <repository>] [--recursive] [--[no-]single-branch] [--] [<path>...]
   or: git submodule [--quiet] set-branch (--default|--branch <branch>) [--] <path>
   or: git submodule [--quiet] set-url [--] <path> <newurl>
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--recursive] [--] [<path>...]
   or: git submodule [--quiet] absorbgitdirs [--] [<path>...]
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1698, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\pfaeff-comfyui\__init__.py", line 15, in <module>
    from .pfaeff import NODE_CLASS_MAPPINGS
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\pfaeff-comfyui\pfaeff.py", line 11, in <module>
    from diffusers import StableDiffusionInpaintPipeline
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\__init__.py", line 30, in <module>
    from .pipelines import OnnxRuntimeModel
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\pipelines\__init__.py", line 19, in <module>
    from .auto_pipeline import AutoPipelineForImage2Image, AutoPipelineForInpainting, AutoPipelineForText2Image
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\pipelines\auto_pipeline.py", line 26, in <module>
    from .deepfloyd_if import IFImg2ImgPipeline, IFInpaintingPipeline, IFPipeline
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\pipelines\deepfloyd_if\__init__.py", line 47, in <module>
    from .pipeline_if import IFPipeline
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\pipelines\deepfloyd_if\pipeline_if.py", line 35, in <module>
    import ftfy
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ftfy\__init__.py", line 15, in <module>
    from ftfy.formatting import display_ljust
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ftfy\formatting.py", line 10, in <module>
    from wcwidth import wcswidth, wcwidth
ModuleNotFoundError: No module named 'wcwidth'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\pfaeff-comfyui module for custom nodes: No module named 'wcwidth'`

**Comment by xxl2005** [comment]
The problem has been solved

copy to:
C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\wcwidth
and
C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\wcwidth-0.2.6.dist-info

from:
C:\Users\Gaming\AppData\Roaming\Python\Python310\site-packages
or
C:\stable-diffusion-webui\venv\Lib\site-packages
